planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  wait_for_initial_state_timeout: 0.0

planning_pipelines:
  pipeline_names: ["ompl"]
  namespace: ""
